import { colors } from '@/constants/colors';
import { createAppStyles } from '@/lib/typography';

export const tagDetailStyles = createAppStyles(
  {
    root: { flex: 1, backgroundColor: colors.bg },
    toolbar: {
      position: 'absolute',
      top: 72,
      left: 0,
      right: 0,
      zIndex: 9,
      width: '100%',
      maxWidth: 880,
      alignSelf: 'center',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 8,
      backgroundColor: colors.bg,
    },
    searchInput: {
      flex: 1,
      height: 36,
      minWidth: 0,
      borderWidth: 0,
      backgroundColor: colors.surface,
      fontSize: 14,
    },
    headerAction: {
      width: 40,
      height: 40,
      flexShrink: 0,
      borderRadius: 20,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    visibilityOptions: { gap: 10 },
    visibilityOption: {
      minHeight: 76,
      padding: 13,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    visibilityOptionSelected: { backgroundColor: colors.surface, borderColor: colors.text },
    visibilityIcon: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.elevated,
      alignItems: 'center',
      justifyContent: 'center',
    },
    visibilityCopy: { flex: 1, minWidth: 0 },
    visibilityLabel: { color: colors.text, fontSize: 13, fontWeight: '700' },
    visibilityDetail: { color: colors.muted, fontSize: 10, lineHeight: 14, marginTop: 3 },
    radio: {
      width: 16,
      height: 16,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.muted,
    },
    radioSelected: { borderWidth: 5, borderColor: colors.text },
    content: {
      width: '100%',
      maxWidth: 880,
      alignSelf: 'center',
      padding: 20,
      paddingTop: 116,
      paddingBottom: 112,
    },
    confirmMessage: { color: colors.text, fontSize: 14, lineHeight: 20 },
    section: { marginTop: 24 },
    categoryDropActive: { backgroundColor: colors.surface, borderRadius: 12 },
    sectionHead: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingBottom: 11,
      borderBottomWidth: 1,
      borderColor: colors.border,
    },
    sectionTitle: { color: colors.muted, fontSize: 12, letterSpacing: 0.2, fontWeight: '600' },
    count: { color: colors.muted, fontSize: 11, fontVariant: ['tabular-nums'] },
    grid: { paddingTop: 16, paddingBottom: 4 },
    gridRow: { gap: '3.5%', marginBottom: 12 },
    card: {
      flex: 1,
      width: '100%',
      maxWidth: '100%',
      minWidth: 0,
      backgroundColor: colors.bg,
    },
    poster: { width: '100%', aspectRatio: 2 / 3, borderRadius: 12 },
    cardTitle: {
      color: colors.text,
      fontSize: 12,
      lineHeight: 16,
      marginTop: 6,
      fontWeight: '600',
    },
    rank: { color: colors.muted },
    row: {
      minHeight: 30,
      width: '100%',
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 4,
      borderRadius: 8,
      gap: 8,
      overflow: 'hidden',
    },
    rowContained: { flex: 1, width: '100%' },
    rowRank: {
      color: colors.muted,
      fontSize: 16,
      lineHeight: 22,
      fontWeight: '600',
      fontVariant: ['tabular-nums'],
      width: 36,
    },
    rowTitleShell: { flex: 1, minWidth: 0, overflow: 'hidden' },
    rowTitle: {
      color: colors.text,
      fontSize: 16,
      lineHeight: 22,
      fontWeight: '500',
      flexShrink: 1,
    },
    rating: {
      color: colors.text,
      fontSize: 16,
      lineHeight: 22,
      fontVariant: ['tabular-nums'],
      width: 34,
      textAlign: 'right',
    },
    pressed: { opacity: 0.72 },
    addButton: {
      position: 'absolute',
      right: 24,
      bottom: 24,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.text,
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 5,
      zIndex: 10,
    },
    addButtonPressed: { opacity: 0.72, transform: [{ scale: 0.97 }] },
    loading: {
      width: '100%',
      maxWidth: 880,
      alignSelf: 'center',
      paddingHorizontal: 20,
      paddingTop: 136,
      gap: 12,
    },
    skeletonRow: {
      height: 30,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    skeletonTitle: {
      width: '58%',
      height: 14,
      borderRadius: 7,
      overflow: 'hidden',
      backgroundColor: colors.elevated,
    },
    skeletonRating: {
      width: 30,
      height: 14,
      borderRadius: 7,
      overflow: 'hidden',
      backgroundColor: colors.elevated,
    },
  },
  [
    'searchInput',
    'visibilityLabel',
    'visibilityDetail',
    'confirmMessage',
    'sectionTitle',
    'count',
    'cardTitle',
    'rank',
    'rowRank',
    'rowTitle',
    'rating',
  ] as const,
);
