import { colors } from '@/constants/colors';
import { createAppStyles } from '@/lib/typography';

export const libraryItemScreenStyles = createAppStyles(
  {
    root: { flex: 1, backgroundColor: colors.bg },
    state: {
      flex: 1,
      width: '100%',
      maxWidth: 760,
      alignSelf: 'center',
      paddingHorizontal: 20,
      paddingTop: 96,
    },
    content: {
      width: '100%',
      maxWidth: 760,
      alignSelf: 'center',
      paddingHorizontal: 20,
      paddingTop: 96,
      paddingBottom: 70,
    },
    hero: { flexDirection: 'row', gap: 18 },
    title: { color: colors.text, fontSize: 27, fontWeight: '800', lineHeight: 31 },
    meta: { color: colors.muted, fontSize: 12, marginTop: 8 },
    genres: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
    overview: { color: colors.muted, fontSize: 14, lineHeight: 22, marginTop: 22 },
    section: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.2,
      borderBottomWidth: 1,
      borderColor: colors.border,
      paddingBottom: 11,
      marginTop: 34,
      marginBottom: 16,
    },
    entry: { gap: 16 },
    entrySummary: { flexDirection: 'row', justifyContent: 'space-between', gap: 16 },
    entryLabel: { color: colors.muted, fontSize: 10, fontWeight: '600', letterSpacing: 0.15 },
    entryValue: { color: colors.text, fontSize: 14, fontWeight: '600', marginTop: 6 },
    entryTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, minHeight: 32 },
    noTags: { color: colors.muted, fontSize: 13, paddingVertical: 7 },
    cast: { width: 82, marginRight: 12 },
    castName: { color: colors.text, fontSize: 11, fontWeight: '600', marginTop: 7 },
    castRole: { color: colors.muted, fontSize: 10, marginTop: 3 },
    episode: { borderBottomWidth: 1, borderColor: colors.border, paddingVertical: 14 },
    epRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: 12 },
    episodeArtwork: {
      width: 112,
      height: 64,
      overflow: 'hidden',
      borderRadius: 10,
      backgroundColor: colors.surface,
    },
    episodeImage: { width: 112, height: 64 },
    episodeImageFallback: {
      position: 'relative',
      overflow: 'hidden',
      width: 112,
      height: 64,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
    },
    episodeImageNumber: {
      color: colors.border,
      fontSize: 26,
      fontWeight: '800',
      fontVariant: ['tabular-nums'],
    },
    epExpand: { flex: 1, minHeight: 64, justifyContent: 'center' },
    epHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
    check: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    epNo: { color: colors.accent, fontVariant: ['tabular-nums'], fontSize: 9, fontWeight: '700' },
    epName: { color: colors.text, fontSize: 14, fontWeight: '600', lineHeight: 18 },
    epOverview: { color: colors.muted, fontSize: 11, lineHeight: 15, marginTop: 4 },
    epTime: { color: colors.muted, fontSize: 9 },
    epActions: { alignItems: 'center', justifyContent: 'center' },
    episodeOptionsButton: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    epDetails: {
      backgroundColor: colors.surface,
      padding: 16,
      gap: 10,
      borderRadius: 12,
      marginBottom: 12,
    },
    epFullOverview: { color: colors.text, fontSize: 13, lineHeight: 20 },
    epFact: { color: colors.muted, fontSize: 11 },
    episodeEditorContent: { gap: 24 },
    drawerTextAction: {
      minHeight: 44,
      alignSelf: 'flex-start',
      justifyContent: 'center',
    },
    drawerTextActionLabel: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
    },
    drawerTextActionDisabled: { opacity: 0.4 },
    inlineError: {
      marginTop: 14,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    errorText: { color: colors.muted, fontSize: 13, flex: 1 },
    seasonAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      paddingVertical: 8,
    },
    seasonProgress: { color: colors.muted, fontSize: 11 },
    seasonProgressSkeleton: {
      position: 'relative',
      overflow: 'hidden',
      width: 104,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.surface,
    },
    tvdbAttribution: {
      color: colors.muted,
      fontSize: 10,
      textAlign: 'center',
      marginTop: 18,
      textDecorationLine: 'underline',
    },
    metadataLoading: {
      minHeight: 92,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
    },
    metadataLoadingText: { color: colors.muted, fontSize: 12 },
    metadataHint: { color: colors.muted, fontSize: 11, marginTop: 8 },
  },
  [
    'title',
    'meta',
    'overview',
    'section',
    'entryLabel',
    'entryValue',
    'noTags',
    'castName',
    'castRole',
    'episodeImageNumber',
    'epNo',
    'epName',
    'epOverview',
    'epTime',
    'epFullOverview',
    'epFact',
    'drawerTextActionLabel',
    'errorText',
    'seasonProgress',
    'tvdbAttribution',
    'metadataLoadingText',
    'metadataHint',
  ] as const,
);
