import { colors } from '@/constants/colors';
import { createAppStyles } from '@/lib/typography';

export const titleDetailScreenStyles = createAppStyles(
  {
    root: { flex: 1, backgroundColor: colors.bg },
    initialPlaceholder: {
      position: 'relative',
      overflow: 'hidden',
      width: 20,
      height: 3,
      marginTop: 20,
      alignSelf: 'center',
      borderRadius: 2,
      backgroundColor: colors.border,
    },
    content: {
      width: '100%',
      maxWidth: 760,
      alignSelf: 'center',
      paddingHorizontal: 20,
      paddingTop: 96,
      paddingBottom: 70,
    },
    state: {
      flex: 1,
      width: '100%',
      maxWidth: 760,
      alignSelf: 'center',
      padding: 20,
      paddingTop: 96,
    },
    hero: { flexDirection: 'row', gap: 18 },
    poster: { width: 122, height: 183 },
    heroCopy: { flex: 1, minWidth: 0 },
    title: { color: colors.text, fontSize: 27, fontWeight: '800', lineHeight: 31 },
    meta: { color: colors.muted, fontSize: 12, marginTop: 8 },
    genres: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
    overview: { color: colors.muted, fontSize: 14, lineHeight: 22, marginTop: 22 },
    facts: { flexDirection: 'row', gap: 12, marginTop: 22 },
    fact: {
      minWidth: 96,
      minHeight: 48,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
    },
    factLabel: { color: colors.muted, fontSize: 9, textTransform: 'uppercase' },
    factValue: { color: colors.text, fontSize: 13, fontWeight: '600', marginTop: 5 },
    placeholder: {
      position: 'relative',
      overflow: 'hidden',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
    },
    chipPlaceholder: { width: 78, height: 32, borderRadius: 16 },
    statPlaceholder: { width: 96, height: 48, borderRadius: 10 },
    castPlaceholder: { width: 72, height: 96, borderRadius: 10, marginRight: 12 },
    episodesPlaceholder: { width: '100%', height: 92, borderRadius: 14 },
    castPlaceholders: { flexDirection: 'row' },
    episodePlaceholders: { gap: 14 },
    section: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.2,
      borderBottomWidth: 1,
      borderColor: colors.border,
      paddingBottom: 11,
      marginTop: 34,
      marginBottom: 16,
    },
    entry: { gap: 16 },
    noEntry: { color: colors.muted, fontSize: 13 },
    cast: { width: 82, marginRight: 12 },
    castImage: { width: 72, height: 96 },
    castName: { color: colors.text, fontSize: 11, fontWeight: '600', marginTop: 7 },
    castRole: { color: colors.muted, fontSize: 10, marginTop: 3 },
    metadataLoading: {
      minHeight: 92,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
    },
    metadataLoadingText: { color: colors.muted, fontSize: 12 },
    titleSkeleton: {
      position: 'relative',
      overflow: 'hidden',
      flexDirection: 'row',
      gap: 18,
      marginTop: 22,
    },
    titleSkeletonPoster: {
      width: 122,
      height: 183,
      borderRadius: 10,
      backgroundColor: colors.surface,
    },
    titleSkeletonCopy: { flex: 1, justifyContent: 'center', gap: 14 },
    skeletonLineTitle: {
      width: '84%',
      height: 22,
      borderRadius: 8,
      backgroundColor: colors.surface,
    },
    skeletonLineShort: {
      width: '22%',
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.surface,
    },
    skeletonLine: { width: '72%', height: 12, borderRadius: 6, backgroundColor: colors.surface },
    skeletonLineLong: { width: '92%', height: 8, borderRadius: 4, backgroundColor: colors.surface },
    seasonProgressSkeleton: {
      position: 'relative',
      overflow: 'hidden',
      width: 104,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.surface,
    },
    inlineError: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 12 },
    errorText: { color: colors.muted, fontSize: 12, flex: 1 },
    episode: { borderBottomWidth: 1, borderColor: colors.border, paddingVertical: 14 },
    epRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: 12 },
    episodeArtwork: {
      width: 112,
      height: 64,
      overflow: 'hidden',
      borderRadius: 10,
      backgroundColor: colors.surface,
    },
    episodeImage: { width: 112, height: 64 },
    episodeImageFallback: {
      position: 'relative',
      overflow: 'hidden',
      width: 112,
      height: 64,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
    },
    episodeImageNumber: {
      color: colors.border,
      fontSize: 26,
      fontWeight: '800',
      fontVariant: ['tabular-nums'],
    },
    epExpand: { flex: 1, minHeight: 64, justifyContent: 'center' },
    epHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
    epNo: { color: colors.accent, fontVariant: ['tabular-nums'], fontSize: 9, fontWeight: '700' },
    epName: { color: colors.text, fontSize: 14, fontWeight: '600', lineHeight: 18 },
    epOverview: { color: colors.muted, fontSize: 11, lineHeight: 15, marginTop: 4 },
    epTime: { color: colors.muted, fontSize: 9 },
    check: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    epDetails: {
      backgroundColor: colors.surface,
      padding: 16,
      gap: 12,
      borderRadius: 12,
      marginBottom: 12,
    },
    epFullOverview: { color: colors.text, fontSize: 13, lineHeight: 20 },
    episodeDate: { color: colors.text, fontSize: 12, fontWeight: '600' },
    episodeHint: { color: colors.muted, fontSize: 11, lineHeight: 16 },
    episodeLoading: { marginVertical: 24 },
    seasonAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      paddingVertical: 8,
    },
    seasonProgress: { color: colors.muted, fontSize: 11 },
    tvdbAttribution: {
      color: colors.muted,
      fontSize: 10,
      textAlign: 'center',
      marginTop: 18,
      textDecorationLine: 'underline',
    },
  },
  [
    'title',
    'meta',
    'overview',
    'factLabel',
    'factValue',
    'section',
    'noEntry',
    'castName',
    'castRole',
    'metadataLoadingText',
    'errorText',
    'episodeImageNumber',
    'epNo',
    'epName',
    'epOverview',
    'epTime',
    'epFullOverview',
    'episodeDate',
    'episodeHint',
    'seasonProgress',
    'tvdbAttribution',
  ] as const,
);
